//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blackjack
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dealer_Hand_DB
    {
        public int Id { get; set; }
        public int d_id { get; set; }
        public int c_value { get; set; }
    
        public virtual Dealer_DB Dealer_DB { get; set; }
    }
}
