//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blackjack
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deck_DB
    {
        public int Id { get; set; }
        public int save_id { get; set; }
        public string image_name { get; set; }
        public int c_value { get; set; }
        public string fname { get; set; }
        public double x_coord { get; set; }
        public double y_coord { get; set; }
        public int z_coord { get; set; }
    
        public virtual Saves_DB Saves_DB { get; set; }
    }
}
