//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blackjack
{
    using System;
    using System.Collections.Generic;
    
    public partial class Players_DB
    {
        public Players_DB()
        {
            this.Player_hands_DB = new HashSet<Player_hands_DB>();
        }
    
        public int player_id { get; set; }
        public int save_id { get; set; }
        public string name { get; set; }
        public int money { get; set; }
        public int total_bet { get; set; }
        public int bet0 { get; set; }
        public int bet1 { get; set; }
        public int bet2 { get; set; }
        public int bet3 { get; set; }
        public int active_hand { get; set; }
        public int nr_of_hands { get; set; }
        public int player_nr { get; set; }
    
        public virtual ICollection<Player_hands_DB> Player_hands_DB { get; set; }
        public virtual Saves_DB Saves_DB { get; set; }
    }
}
